### PR TITLE
Invoice view

### PR DESCRIPTION
**Pull request by Umoren**
This the Invoce-View Page branch.

Developers working on this branch are:
@franeldev 
@OmotosoYusuf 
@Janetsomehow 
@Umoren

### CODE REVIEW

**Comment by fabianuzukwu** [comment]
please reply with screenshot of the result of your codes

**Comment by fabianuzukwu** [comment]
so that i can merge

**Comment by Umoren** [comment]
We are still working on the page.
I'll inform you when we are done

**Comment by phiiileo** [comment]
There is nothing on your page

**Comment by OmotosoYusuf** [comment]
I don't have a page, I did my work on the invoice-view.html page and I also
found some code there already.

**Pull request closed without merging**
