### PR TITLE
Estimate page tomisin

### PR DESCRIPTION
**Pull request by TomisinAjayi**
An Estimate page created for new users.

### CODE REVIEW

**Comment by Eronmmer** [comment]
Please leave detailed description and screenshots in case of next time. By the way, someone already made a PR with the same thing you just did here.

**Comment by fabianuzukwu** [comment]
drop your screenshot please

**Comment by TomisinAjayi** [comment]
alright
estimate page for new users

**Comment by phiiileo** [comment]
Ensure your page is responsive and mobile-friendly, after which you can send another PR. I will close this PR. Thanks

**Pull request closed without merging**
