### PR TITLE
updates on forgotpassword n changepassword

### PR DESCRIPTION
**Pull request by Abdulwasiu22**

### CODE REVIEW

**Comment by serignoleba** [comment]
URL link to test

**Comment by Abdulwasiu22** [comment]
https://josephelegbua.github.io/Lancer/forgotpassword.html, https://josephelegbua.github.io/Lancer/changepassword.html

**Comment by phiiileo** [comment]
Please update your repo before sending another pr

**Comment by KingAbesh** [comment]
lool babe weak me

**Comment by Eronmmer** [comment]
😹 😂

**Pull request closed without merging**
