### PR TITLE
Lancer contact support page

### PR DESCRIPTION
**Pull request by seunbayo**
work by @slarin and @seunbayo

### CODE REVIEW

**Comment by fabianuzukwu** [comment]
I can't merge, many conflicts ... change the name of your file, screenshot and create pull request again.... include the screenshot of the resquest..... please make sure it follow the design

**Comment by slarin** [comment]
Changes made. No conflicts anymore.

Live code: [http://magenta-war.surge.sh/](url)

**Comment by serignoleba** [comment]
Conflicting files
README.md
contact-support.html

**Comment by slarin** [comment]
I've just seen that someone else has worked on the contact-support page and pushed it to the repo. They have the same names but obviously different code. My @seunbayo and I did this first, and sorted out all the issues hours ago. It wasn't pulled then.

I'll delete the readme and add(2) to the html's name. That should sort it.

**Comment by slarin** [comment]
sorted again. Please pull as soon as you can.

**Comment by serignoleba** [comment]
1. Please make sure your work matches the design.
2. The page is not mobile responsive, it needs to be.
3. Why are the icons not showing?
Please work on these and create a new pull request

**Pull request closed without merging**
