### PR TITLE
Edit invoice

### PR DESCRIPTION
**Pull request by zonebyte**
This is the edit invoice page. Please merge. It is full HTML and CSS. Pictures coming soon

### CODE REVIEW

**Comment by zonebyte** [comment]
This is the cloudinary picture links
https://res.cloudinary.com/drpk8jfdq/image/upload/v1570658299/captue2_hlghyl.png
https://res.cloudinary.com/drpk8jfdq/image/upload/v1570658299/captue2_hlghyl.png

**Comment by serignoleba** [comment]
The mobile responsive is very much off

**Comment by Josh4324** [comment]
Nice job so far, please follow the figma design to the letter.
Refresh your figma design to confirm if you are on the right path

**Comment by zonebyte** [comment]
Someone already closed the pull request. Cited responsiveness

**Comment by zonebyte** [comment]
@serignoleba and @Josh4324 Please check this

https://res.cloudinary.com/drpk8jfdq/image/upload/v1570658704/Screenshot_20191009-225923_tznpy6.png

**Pull request closed without merging**
