### PR TITLE
Contact Support page

### PR DESCRIPTION
**Pull request by slarin**
made the requested changes. fixed the image resolution on mobile screens.

live code: [http://magenta-war.surge.sh/](url)

### CODE REVIEW

**Comment by phiiileo** [comment]
Dead url for testing

**Comment by slarin** [comment]
URL here: [http://magenta-war.surge.sh/](url)

**Comment by phiiileo** [comment]
Not mobile friendly

**Comment by slarin** [comment]
Could you please be more specific, is there something wrong with the sidebar or header?

It is mobile responsive.

**Pull request closed without merging**
