### PR TITLE
html of edit invoice

### PR DESCRIPTION
**Pull request by preciouskk**
edit invoice html

### CODE REVIEW

**Comment by serignoleba** [comment]
Please drop screenshot of your work

**Comment by zonebyte** [comment]
It's just a HTML structure of the page. The CSS will be added. It's created on a separate branch edit-invoice branch

**Comment by serignoleba** [comment]
When you have everything ready, make a new pull request. And also make sure the css is internal. No external css

**Comment by serignoleba** [comment]
It doesn't match the design and it isn't mobile responsive. Please work on it and submit a new pull request.

**Comment by serignoleba** [comment]
1. It isn't mobile responsive.
2. Some pages do not match the design given

**Pull request closed without merging**
