### PR TITLE
Update on the Pricing page

### PR DESCRIPTION
**Pull request by Itunuoluwao**

### CODE REVIEW

**Comment by Eronmmer** [comment]
There's already a pricing page in the repo...

**Comment by Eronmmer** [comment]
How is yours different from the one there originally?

**Comment by Itunuoluwao** [comment]
I and my Partner was assigned the Lancer Pricing page earlier today. I see
no reason someone else will create that. Also if there is any change, I
think we ought to know.

I have been at work and trying to code this page. This is not a good way to
treat team members. Kindly look into this.

**Comment by fabianuzukwu** [comment]
Please the owner of this pull request should drop the screenshot of the result of his codes

**Comment by Itunuoluwao** [comment]
Can I send another PR that shows the screenshot since I can’t put picture
in the comment

**Comment by fabianuzukwu** [comment]
Please the owner of this pull request should drop the screenshot of the result of his codes

**Pull request merged**
