### PR TITLE
trackpoject-passwordreset-messages

### PR DESCRIPTION
**Pull request by josephelegbua**
**LINKS TO PAGES**

1. Track project - https://josephelegbua.github.io/Lancer/trackproject.html
2. Forgot Password - https://josephelegbua.github.io/Lancer/forgotpassword
3. Password reset successful - https://josephelegbua.github.io/Lancer/passwordresetmessage.html
4. Password reset Confirmation - https://josephelegbua.github.io/Lancer/passwordresetconfirmation.html
5. Change Password - https://josephelegbua.github.io/Lancer/changepassword

### CODE REVIEW

**Comment by josephelegbua** [comment]
change password page was done by (@Omowunmi HNG) - Slack

**Comment by josephelegbua** [comment]
linked logo to homepage

**Comment by phiiileo** [comment]
What exactly did you do on these files?

**Comment by josephelegbua** [comment]
trackproject.html, passwordresetmessage.html, passwordresetconfirmation.html (done by me, @Joseph Elegbua - Slack)

forgotpassword (done by @AbdulwasiuBalogun - Slack)

change password (done by @Omowunmi HNG - Slack)

**Comment by josephelegbua** [comment]
i only made changes to the files i worked on

**Comment by serignoleba** [comment]
The logos are weird looking not the same color

**Pull request closed without merging**
