### PR TITLE
Fixed styles, text, responsiveness, and links for Pricing page.

### PR DESCRIPTION
**Pull request by Dev-Nebe**
Before
Before_

After
dev-nebe github io_Lancer_

Test link for what it looks like now with fixes: https://dev-nebe.github.io/Lancer/

### CODE REVIEW

**Comment by Dev-Nebe** [comment]
Test link for what it looked like before I fixed it: https://olodestone.github.io/lancer.test/pricing.html

**Comment by fabianuzukwu** [comment]
the link styling still look somehow.... check for the reusable footer

**Comment by Dev-Nebe** [comment]
Which of the links? And where is the footer located so I can add it?

**Comment by Dev-Nebe** [comment]
Done, you can check it out again using this link https://dev-nebe.github.io/Lancer/

**Comment by Dev-Nebe** [comment]
Note that the Lancer Logo in the footer is not currently being displayed as this is a general issue. I've raised an issue on the index.html page asking for the hosting of the logo to be fixed so it'll work across all pages using that footer.

**Pull request merged**
