### PR TITLE
Lancer active page

### PR DESCRIPTION
**Pull request by Young-Einstein10**
updated repo

### CODE REVIEW

**Comment by phiiileo** [comment]
Test url and your Pr is confusing sort of

**Comment by Young-Einstein10** [comment]
Page url: https://young-einstein10.github.io/lancer-project-status-Active/

**Comment by phiiileo** [comment]
You have too many deletions in your repo, that is going to affect the repo if I merged, please see to those changes. i.e update your repo

**Comment by Young-Einstein10** [comment]
i have already done <git fetch upstream master> to update my repo on my end....what do u suggest i do bcuz everything is up to date on my end

**Pull request closed without merging**
